version: '3'

networks:
  net:

services:

  postgres:
    image: postgres:14.0
    container_name: postgresTTT
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - net
    ports:
      - "8001:5432"

  judge:
    build:
      context: /judgeService
      dockerfile: Dockerfile
    container_name: judge
    image: judge_image
    env_file:
      - .env
    volumes:
      - ./judgeService/scoresVol:/app/scoresVol
    networks:
      - net
    ports:
      - "8000:8000"

  player1:
    build:
      context: /player1Service
      dockerfile: Dockerfile
    container_name: player1
    image: player1_image
    env_file:
      - .env
    networks:
      - net

  player2:
    build:
      context: /player2Service
      dockerfile: Dockerfile
    container_name: player2
    image: player2_image
    env_file:
      - .env
    networks:
      - net